.gitignore
src/main/scala/strawman/collection/Iterable.scala
src/main/scala/strawman/collection/IterableOnce.scala
src/main/scala/strawman/collection/Iterator.scala
src/main/scala/strawman/collection/Seq.scala
src/main/scala/strawman/collection/Set.scala
src/main/scala/strawman/collection/View.scala
src/main/scala/strawman/collection/immutable/Iterable.scala
src/main/scala/strawman/collection/immutable/LazyList.scala
src/main/scala/strawman/collection/immutable/List.scala
src/main/scala/strawman/collection/immutable/Seq.scala
src/main/scala/strawman/collection/mutable/ArrayBuffer.scala
src/main/scala/strawman/collection/mutable/Builder.scala
src/main/scala/strawman/collection/mutable/Growable.scala
src/main/scala/strawman/collection/mutable/Iterable.scala
src/main/scala/strawman/collection/mutable/Iterator.scala
src/main/scala/strawman/collection/mutable/ListBuffer.scala
src/main/scala/strawman/collection/mutable/Seq.scala
src/main/scala/strawman/collection/mutable/Set.scala
src/main/scala/strawman/collection/package.scala
src/test/scala/strawman/collection/test/Test.scala

- adds {mutable,immutable}.Iterable
- adds immutable.Seq
- fleshes out inheritance of ...Like traits so that all collection
base traits transform to themselves.
The design is similar to current collections, in that `map` and other transformers are supported on all collections. I wanted to create that as a baseline first. We can then see what it would take to remove some of this functionality for strict mutable collections and general collections.
It's based on the "add mutable collections" PR.

Add base traits of collection hierarchy

---

benchmarks/memory/src/main/scala/strawman/collection/MemoryFootprint.scala
build.sbt

- Fork tests using JOL to give it a regular classpath to introspect, rather than the exotic one that SBT in-process running ends up with.
- Avoid apparent scalac bug with `DelayedInit`, that manifest as:
```
java.lang.IncompatibleClassChangeError: strawman.collection.MemoryFootprint and strawman.collection.MemoryFootprint$delayedInit$body disagree on InnerClasses attribute
```

make JOL work

---

README.md
benchmarks/memory/src/main/scala/strawman/collection/MemoryFootprint.scala
benchmarks/time/src/main/scala/strawman/collection/immutable/LazyListBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/immutable/ListBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/immutable/ScalaListBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/mutable/ArrayBufferBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/mutable/ListBufferBenchmark.scala
build.sbt
project/Bencharts.scala
project/plugins.sbt
src/main/scala/strawman/collection/Iterable.scala
src/main/scala/strawman/collection/View.scala
src/main/scala/strawman/collection/immutable/LazyList.scala
src/main/scala/strawman/collection/immutable/List.scala
src/main/scala/strawman/collection/mutable/ArrayBuffer.scala

This PR adds a few micro-benchmarks that may help us to get some numbers when tuning our implementations.
I was not able to produce nice charts, the output is text-only (/cc @axel22).

Add micro-benchmarks

---

src/main/scala/strawman/collection/Iterable.scala
src/main/scala/strawman/collection/Map.scala
src/main/scala/strawman/collection/Seq.scala
src/main/scala/strawman/collection/Set.scala
src/main/scala/strawman/collection/Sorted.scala
src/main/scala/strawman/collection/View.scala
src/main/scala/strawman/collection/immutable/HashSet.scala
src/main/scala/strawman/collection/immutable/Map.scala
src/main/scala/strawman/collection/immutable/Set.scala
src/main/scala/strawman/collection/immutable/SortedMap.scala
src/main/scala/strawman/collection/immutable/SortedSet.scala
src/main/scala/strawman/collection/immutable/TreeMap.scala
src/main/scala/strawman/collection/immutable/TreeSet.scala
src/main/scala/strawman/collection/mutable/HashMap.scala
src/main/scala/strawman/collection/mutable/HashSet.scala
src/main/scala/strawman/collection/mutable/Map.scala
src/main/scala/strawman/collection/mutable/Set.scala
src/test/scala/strawman/collection/test/Test.scala

I sketched the integration of `Set`, `TreeSet`, `Map` and `TreeMap` collections. They were challenging because `Map` takes two type parameters where previous collections were only taking one type parameter, and also because `TreeSet` and `TreeMap` take an additional implicit `Ordering` parameter.
This is an alternative to #23 that makes `Set` extend `Iterable` and `SortedSet` have two overloads of `map` (one has an additional implicit `Ordering` parameter).

Overloading based implementation of Set, TreeSet, Map and TreeMap

---

src/main/scala/strawman/collection/Iterable.scala
src/main/scala/strawman/collection/IterableFactories.scala
src/main/scala/strawman/collection/IterableFactory.scala
src/main/scala/strawman/collection/Map.scala
src/main/scala/strawman/collection/Sorted.scala
src/main/scala/strawman/collection/immutable/HashSet.scala
src/main/scala/strawman/collection/immutable/LazyList.scala
src/main/scala/strawman/collection/immutable/List.scala
src/main/scala/strawman/collection/immutable/SortedMap.scala
src/main/scala/strawman/collection/immutable/TreeMap.scala
src/main/scala/strawman/collection/immutable/TreeSet.scala
src/main/scala/strawman/collection/mutable/ArrayBuffer.scala
src/main/scala/strawman/collection/mutable/HashSet.scala
src/main/scala/strawman/collection/mutable/ListBuffer.scala
src/test/scala/strawman/collection/test/TraverseTest.scala

Also, define an implicit builder factory `() => Builder[A, C[A]]` that can be used by end-users to retrieve a factory for a given collection type. For instance we can now write `Future.sequence` (or equivalent) as follows:
~~~ scala
def futureSequence[A, C[X] <: Iterable[X]](xs: C[Future[A]])(implicit canBuild: () => Builder[A, C[A]]): Future[C[A]] =
xs.foldLeft(Future.successful(canBuild.apply())) { (fr, fa) =>
fr.zipWith(fa)(_ += _)
}.map(_.result)
~~~
Note that I duplicated the collection factories: `IterableFactory` works only for collection types of kind `* -> *`, `OrderingGuidedFactory` works for the same kind of collection types but requires an implicit `Ordering`, `MapFactory` works for collection types of kind `* -> * -> *`, and `SortedMapFactory` is the same but requires an …

Make the different kinds of collection companions consistent together

---

src/main/scala/strawman/collection/mutable/ArrayBuffer.scala

Before:
```scala
scala> strawman.collection.mutable.ArrayBuffer(1,2,3,4,5).view
res0: strawman.collection.mutable.ArrayBufferView[Nothing] = ArrayBufferView(1, 2, 3, 4, 5)
```
After:
```scala
scala> strawman.collection.mutable.ArrayBuffer(1,2,3,4,5).view
res0: strawman.collection.mutable.ArrayBufferView[Int] = ArrayBufferView(1, 2, 3, 4, 5)
```

Fix minor ArrayBufferView type inference problem

---

.travis.yml
build.sbt
project/build.properties
src/main/scala/strawman/collection/BuildFrom.scala
src/main/scala/strawman/collection/Set.scala
src/main/scala/strawman/collection/immutable/HashSet.scala
src/main/scala/strawman/collection/immutable/ListSet.scala
src/main/scala/strawman/collection/immutable/RedBlackTree.scala
src/main/scala/strawman/collection/immutable/TrieIterator.scala
src/test/scala/strawman/collection/test/Test.scala
src/test/scala/strawman/collection/test/TraverseTest.scala

This PR includes work from @odersky and @biboudis as well as additional stuff to support cross compilation for both Scala 2.12 and Dotty.
I still have execution errors when running the tests:
~~~
Test strawman.collection.test.StrawmanTest.mainTest failed: java.lang.IncompatibleClassChangeError: Conflicting default methods: strawman/collection/SeqLike.coll strawman/collection/Iterable.coll
~~~

Dotty support

---

src/main/scala/strawman/collection/BuildFrom.scala
src/main/scala/strawman/collection/Set.scala
src/main/scala/strawman/collection/immutable/HashSet.scala
src/main/scala/strawman/collection/immutable/ListSet.scala
src/main/scala/strawman/collection/immutable/RedBlackTree.scala
src/main/scala/strawman/collection/immutable/TrieIterator.scala
src/test/scala/strawman/collection/test/TraverseTest.scala

This is a set of changes needed to compile the strawman under dotty. The first 4 commits are simple rewrites or only concern some details. The next two commits are more problematic.
fc09109 shows a failure to infer the right type instance of `buildFromConstrainedPolyBuildable`
It's signature is the epic
implicit def buildFromConstrainedPolyBuildable[Ev[_], CC[_], Impl[_], A, E : Ev]: BuildFrom[ConstrainedPolyBuildable[A, CC, Ev], E] { type To = CC[E] }
Btw, `Impl[_]` is unused - why are we adding a 5th type parameter here? 
I have no idea why dotty fails to find in the implicit, and in fact have no idea how an implicit os supposed to be found in the first place. Can someone explain the intended sequence of instantiations here?
a475189 shows a failure of type inference due to union types. …

Compile under dotty

---

README.md
src/main/scala/strawman/collection/Iterable.scala
src/main/scala/strawman/collection/Map.scala
src/main/scala/strawman/collection/Set.scala
src/main/scala/strawman/collection/immutable/HashMap.scala
src/main/scala/strawman/collection/immutable/HashSet.scala
src/main/scala/strawman/collection/immutable/List.scala
src/main/scala/strawman/collection/immutable/ListMap.scala
src/main/scala/strawman/collection/immutable/ListSet.scala
src/main/scala/strawman/collection/immutable/Map.scala
src/main/scala/strawman/collection/immutable/Set.scala
src/main/scala/strawman/collection/immutable/TreeMap.scala
src/main/scala/strawman/collection/immutable/TreeSet.scala
src/main/scala/strawman/collection/mutable/ArrayBuffer.scala
src/main/scala/strawman/collection/mutable/Builder.scala
src/main/scala/strawman/collection/mutable/Growable.scala
src/main/scala/strawman/collection/mutable/HashMap.scala
src/main/scala/strawman/collection/mutable/HashSet.scala
src/main/scala/strawman/collection/mutable/ImmutableMapBuilder.scala
src/main/scala/strawman/collection/mutable/ImmutableSetBuilder.scala
src/main/scala/strawman/collection/mutable/ListBuffer.scala
src/main/scala/strawman/collection/mutable/Map.scala
src/main/scala/strawman/collection/mutable/Set.scala

Fixes #46.
I systematically added methods with alphanumeric names for all operations and defined symbolic operators as aliases.
I suffixed operations on mutable collections with `InPlace`, since that’s the new convention.

Provide alphanumeric methods with descriptive names as alternatives to symbolic operators

---

src/main/scala/strawman/collection/Hashing.scala
src/main/scala/strawman/collection/immutable/HashMap.scala
src/main/scala/strawman/collection/immutable/HashSet.scala

In order to simplify the inheritance graph, I moved the code shared by `HashSet` and `HashMap` into an object rather than an inherited trait.

Use delegation over inheritance

---

.gitignore
src/main/scala/strawman/collection/BitSet.scala
src/main/scala/strawman/collection/BuildFrom.scala
src/main/scala/strawman/collection/Iterable.scala
src/main/scala/strawman/collection/IterableFactories.scala
src/main/scala/strawman/collection/Map.scala
src/main/scala/strawman/collection/SortedSet.scala
src/main/scala/strawman/collection/immutable/BitSet.scala
src/main/scala/strawman/collection/immutable/HashMap.scala
src/main/scala/strawman/collection/immutable/ListMap.scala
src/main/scala/strawman/collection/immutable/Map.scala
src/main/scala/strawman/collection/immutable/Set.scala
src/main/scala/strawman/collection/immutable/SortedMap.scala
src/main/scala/strawman/collection/immutable/SortedSet.scala
src/main/scala/strawman/collection/immutable/TreeMap.scala
src/main/scala/strawman/collection/immutable/TreeSet.scala
src/main/scala/strawman/collection/mutable/Growable.scala
src/main/scala/strawman/collection/mutable/Map.scala
src/main/scala/strawman/collection/mutable/Set.scala
src/main/scala/strawman/collection/mutable/SortedSet.scala
src/test/scala/strawman/collection/test/Test.scala
src/test/scala/strawman/collection/test/TraverseTest.scala

Changes to compile latest master under dotty.
This compiles with the dotty compiler in https://github.com/lampepfl/dotty/pull/2240.
There's a known problem in parameter forwarding, so for the moment you need to compile with
-Ysuppress-param-forwarding.
Also for the moment you need to compile with a 2.12 version of Either that starts as follows:
sealed abstract class Either[+A, +B] extends Product1[A | B] with Serializable { ...
If you don't do that, type inference will yield the wrong type in TraverseTest.eitherSequence. We should check whether there's something we can do in the library design about this.

Compile under dotty, V2

---

src/main/scala/strawman/collection/mutable/Growable.scala
src/main/scala/strawman/collection/mutable/HashMap.scala
src/main/scala/strawman/collection/mutable/Iterable.scala
src/main/scala/strawman/collection/mutable/Map.scala
src/main/scala/strawman/collection/mutable/Seq.scala
src/main/scala/strawman/collection/mutable/Set.scala
src/main/scala/strawman/collection/mutable/Shrinkable.scala
src/main/scala/strawman/collection/mutable/TreeMap.scala

This PR introduces *more* abstractions to get consistent operations between mutable collections. For instance, in `mutable.Set` the `mapInPlace` method was previously returning `Unit` whereas in `ListBuffer` it was returning `this.type`. This is fixed by this PR: the `mapInPlace` method is now defined in `mutable.Iterable`.

Flesh out the mutable type hierarchy

---

src/main/scala/strawman/collection/Factories.scala
src/main/scala/strawman/collection/Set.scala
src/main/scala/strawman/collection/SortedMap.scala
src/main/scala/strawman/collection/SortedSet.scala
src/main/scala/strawman/collection/immutable/ListSet.scala
src/main/scala/strawman/collection/immutable/Seq.scala
src/main/scala/strawman/collection/immutable/Set.scala
src/main/scala/strawman/collection/immutable/SortedSet.scala
src/main/scala/strawman/collection/immutable/TreeMap.scala
src/main/scala/strawman/collection/immutable/TreeSet.scala
src/main/scala/strawman/collection/mutable/ArrayBuffer.scala
src/main/scala/strawman/collection/mutable/BitSet.scala
src/main/scala/strawman/collection/mutable/Growable.scala
src/main/scala/strawman/collection/mutable/HashMap.scala
src/main/scala/strawman/collection/mutable/HashSet.scala
src/main/scala/strawman/collection/mutable/ListBuffer.scala
src/main/scala/strawman/collection/mutable/SortedSet.scala
src/main/scala/strawman/collection/mutable/TreeMap.scala
src/main/scala/strawman/collection/mutable/TreeSet.scala

- Removes the `FromIterable` trait, which was only inherited from `IterableFactory`, and harmonizes the names used in the `Factories.scala` file.
- Systematically uses delegate factories for abstract collections.
- Factors out the implementation of `fromIterable` for mutable collections (into a `Growable.fromIterable` method).

Harmonize factories

---

src/main/scala/strawman/collection/Map.scala
src/main/scala/strawman/collection/SortedMap.scala
src/main/scala/strawman/collection/SortedOps.scala
src/main/scala/strawman/collection/immutable/Map.scala
src/main/scala/strawman/collection/immutable/SortedMap.scala
src/test/scala/strawman/collection/test/Test.scala

In SortedMap, override the return type of map operations that are polymorphic in values only

---

src/main/scala/strawman/collection/ArrayOps.scala
src/main/scala/strawman/collection/Factories.scala
src/main/scala/strawman/collection/Iterable.scala
src/main/scala/strawman/collection/SortedMap.scala
src/main/scala/strawman/collection/SortedSet.scala
src/main/scala/strawman/collection/StringOps.scala
src/main/scala/strawman/collection/View.scala
src/main/scala/strawman/collection/immutable/BitSet.scala
src/main/scala/strawman/collection/immutable/HashMap.scala
src/main/scala/strawman/collection/immutable/HashSet.scala
src/main/scala/strawman/collection/immutable/LazyList.scala
src/main/scala/strawman/collection/immutable/List.scala
src/main/scala/strawman/collection/immutable/ListMap.scala
src/main/scala/strawman/collection/immutable/ListSet.scala
src/main/scala/strawman/collection/immutable/SortedMap.scala
src/main/scala/strawman/collection/immutable/SortedSet.scala
src/main/scala/strawman/collection/immutable/TreeMap.scala
src/main/scala/strawman/collection/immutable/TreeSet.scala
src/main/scala/strawman/collection/mutable/ArrayBuffer.scala
src/main/scala/strawman/collection/mutable/BitSet.scala
src/main/scala/strawman/collection/mutable/HashSet.scala
src/main/scala/strawman/collection/mutable/ListBuffer.scala
src/main/scala/strawman/collection/mutable/Map.scala
src/main/scala/strawman/collection/mutable/SortedSet.scala
src/main/scala/strawman/collection/mutable/TreeMap.scala
src/main/scala/strawman/collection/mutable/TreeSet.scala
src/test/scala/strawman/collection/test/TraverseTest.scala

Every collection now has a `iterableFactory` method that returns the `IterableFactory` associated with the collection type. `fromIterable` now is defined only once in terms of `IterableFactory`. 
This lets us revive fully generic forms of `TraverseTest`.
We could go further and have a subset of Factories that have `newBuilder` methods. (Lazy collections should not offer such a method). We could then avoid using an intermediate collection in traverse test for the building, and instead use the builder of the target collection directly.

Expose factories

---

benchmarks/memory/src/main/scala/strawman/collection/MemoryFootprint.scala
benchmarks/time/src/main/scala/strawman/collection/immutable/ArrayBaselineBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/immutable/ArrayViewBenchmark.scala
benchmarks/timeJava8/src/main/java/streams/Java8Streams.java
build.sbt

This set could be useful for examining, through experimentation, to see whether the finally executed code was fused, and by comparing it with the baseline set, to check whether inline+specialization gave interesting results. This would be also interesting for quickly testing auto specialization in dotty compared with the baseline or even Java 8 streams.
I have ported some of these stream benchmarks (or Views in Scala parlance) from our Stream Fusion, to Completeness paper ([pdf](https://arxiv.org/pdf/1612.06668.pdf)).
WDYT?

Add ArrayView benchmarks (and baseline)

---

src/main/scala/strawman/collection/Map.scala

Fixes #82.
The implementation has been copied from the current collections.

Implement equality for Map collection type

---

README.md
benchmarks/time/src/main/scala/strawman/collection/immutable/HashSetBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/immutable/ImmutableArrayBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/immutable/LazyListBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/immutable/ListBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/immutable/PrimitiveArrayBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/immutable/ScalaHashSetBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/immutable/ScalaListBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/immutable/ScalaTreeSetBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/immutable/ScalaVectorBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/immutable/TreeSetBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/mutable/ArrayBufferBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/mutable/ListBufferBenchmark.scala
src/main/scala/strawman/collection/Iterable.scala
src/main/scala/strawman/collection/Map.scala
src/main/scala/strawman/collection/immutable/BitSet.scala
src/main/scala/strawman/collection/immutable/HashMap.scala
src/main/scala/strawman/collection/immutable/ImmutableArray.scala
src/main/scala/strawman/collection/immutable/LazyList.scala
src/main/scala/strawman/collection/immutable/TreeSet.scala
src/main/scala/strawman/collection/mutable/HashMap.scala
src/main/scala/strawman/collection/mutable/HashTable.scala
src/main/scala/strawman/collection/mutable/Map.scala

I rebased #108 on top of #110. Now all the collections reuse the same implementation of `groupBy`.

Add groupBy (on top of #110)

---

src/main/scala/strawman/collection/Iterable.scala
src/main/scala/strawman/collection/package.scala
src/test/scala/strawman/collection/test/FlattenTest.scala

This is based on szeiger:wip/constrained-collections2. I only added the [last commit](https://github.com/scala/collection-strawman/pull/48/commits/960ce6a17d226c2bbe5344e0e81bc7e29f9455ce) to check that `flatten` would work with `Iterable[Option[?]]` values. This requires `flatten` to take an implicit view parameter and to define an implicit conversion from `Option[A]` to `Iterable[A]` (as it is currently the case in 2.12).
I also checked that it was possible to use `flatMap` with a function returning an `Option[?]` (instead of the expected `IterableOnce[?]`), which is a common pattern I think.

Flatten and interaction between flatMap and Options

---

README.md
src/main/scala/strawman/collection/Iterable.scala
src/main/scala/strawman/collection/Iterator.scala
src/main/scala/strawman/collection/View.scala
src/main/scala/strawman/collection/immutable/ImmutableArray.scala
src/main/scala/strawman/collection/immutable/List.scala
src/main/scala/strawman/collection/immutable/NumericRange.scala
src/main/scala/strawman/collection/immutable/Range.scala
src/main/scala/strawman/collection/immutable/TreeMap.scala
src/main/scala/strawman/collection/immutable/TreeSet.scala
src/main/scala/strawman/collection/mutable/TreeMap.scala
src/main/scala/strawman/collection/mutable/TreeSet.scala
src/test/scala/strawman/collection/test/Test.scala

Essentially, the approach is to implement them directly in `IterableOps` when they are “terminal” methods (e.g. `max`, `reduce`) and to have a view based implementation when a collection is returned (e.g. `dropWhile`, `scanLeft`). When we return a collection but have no other choice than consuming all the elements (e.g. `scanRight`), a custom implementation is done in `IterableOps`.
Fixes #119.

Add most of the current methods of Traversable to IterableOps

---

src/main/scala/strawman/collection/immutable/HashMap.scala

Probably dont need this case
https://travis-ci.org/scala/collection-strawman#L1056
```
[warn] -- [E029] Match case Unreachable Warning: /home/travis/build/scala/collection-strawman/src/main/scala/strawman/collection/immutable/HashMap.scala:575:13 
[warn] 575 |      case _ => sys.error("section supposed to be unreachable.")
[warn]     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[warn]     |             unreachable code
[warn] one warning found
```

Clean up Match case Unreachable Warning

---

src/main/scala/strawman/collection/ArrayOps.scala
src/main/scala/strawman/collection/Iterator.scala
src/main/scala/strawman/collection/LinearSeq.scala
src/main/scala/strawman/collection/Map.scala
src/main/scala/strawman/collection/Seq.scala
src/main/scala/strawman/collection/Set.scala
src/main/scala/strawman/collection/StringOps.scala
src/main/scala/strawman/collection/View.scala
src/main/scala/strawman/collection/immutable/ImmutableArray.scala
src/main/scala/strawman/collection/immutable/ListMap.scala
src/main/scala/strawman/collection/immutable/NumericRange.scala
src/main/scala/strawman/collection/immutable/Range.scala
src/main/scala/strawman/collection/immutable/RedBlackTree.scala
src/main/scala/strawman/collection/immutable/TrieIterator.scala
src/main/scala/strawman/collection/immutable/Vector.scala
src/main/scala/strawman/collection/mutable/ArrayBuffer.scala
src/main/scala/strawman/collection/mutable/HashMap.scala
src/main/scala/strawman/collection/mutable/ListBuffer.scala
src/main/scala/strawman/collection/mutable/RedBlackTree.scala

Add `@throws` annotations for `Map.apply`, `Seq.apply` and `Iterator.next()`.
Fix two cases where iterators did not bounds check.
Attempts to resolve #152 (though I may not have thought of some methods which should have `@throws` annotations).

Add `@throws` annotations; fix iterators

---

src/main/scala/strawman/collection/Iterable.scala
src/main/scala/strawman/collection/Iterator.scala
src/main/scala/strawman/collection/View.scala
src/main/scala/strawman/collection/mutable/ArrayBuffer.scala
src/main/scala/strawman/collection/mutable/Builder.scala
src/main/scala/strawman/collection/mutable/GrowableBuilder.scala

Fixes #131.
Note that I kept the `grouped` and `sliding` methods of `Iterator` even though they also use buffers. Since these methods do exist in 2.12 we have to discuss before we remove them…

Remove dropRight and takeRight from Iterator

---

src/main/scala/strawman/collection/LinearSeq.scala

As noticed by @Ichoran, when a method aliases another method, it’s better to make it final.

Make `length` implementation final in LinearSeq.

---

benchmarks/time/src/main/scala/strawman/collection/immutable/ListBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/immutable/ScalaListBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/immutable/ScalaVectorBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/immutable/VectorBenchmark.scala
src/main/scala/strawman/collection/ArrayOps.scala
src/main/scala/strawman/collection/StrictOptimizedIterableOps.scala
src/main/scala/strawman/collection/StringOps.scala
src/main/scala/strawman/collection/View.scala
src/main/scala/strawman/collection/immutable/BitSet.scala
src/main/scala/strawman/collection/immutable/HashMap.scala
src/main/scala/strawman/collection/immutable/HashSet.scala
src/main/scala/strawman/collection/immutable/ImmutableArray.scala
src/main/scala/strawman/collection/immutable/List.scala
src/main/scala/strawman/collection/immutable/ListMap.scala
src/main/scala/strawman/collection/immutable/ListSet.scala
src/main/scala/strawman/collection/immutable/NumericRange.scala
src/main/scala/strawman/collection/immutable/Range.scala
src/main/scala/strawman/collection/immutable/StrictOptimizedSeqOps.scala
src/main/scala/strawman/collection/immutable/TreeMap.scala
src/main/scala/strawman/collection/immutable/TreeSet.scala
src/main/scala/strawman/collection/immutable/Vector.scala
src/main/scala/strawman/collection/mutable/ArrayBuffer.scala
src/main/scala/strawman/collection/mutable/BitSet.scala
src/main/scala/strawman/collection/mutable/GrowableBuilder.scala
src/main/scala/strawman/collection/mutable/HashMap.scala
src/main/scala/strawman/collection/mutable/HashSet.scala
src/main/scala/strawman/collection/mutable/ListBuffer.scala
src/main/scala/strawman/collection/mutable/TreeMap.scala
src/main/scala/strawman/collection/mutable/TreeSet.scala

Fixes #125.
We get a performance boost on some collection types by overriding some operations to use strict builders. For instance, here is the benchmark for `span` on `Vector`:
Here is the benchmark for `append` on `List`:
Some operations are worse when implemented on top of builders (so, for those, I kept the view-based implementation). E.g. `padTo` on `List`:
I’m still not 100% sure it is worth adding this `StrictOptimizedSeqOps` trait because it is currently inherited only by `Vector`, `List` and `ImmutableArray`, but only `List` actually benefits from the optimizations brought to `append` and `updated` because `Vector` and `ImmutableArray` override these operations anyway. Maybe we should just override `List` methods without introducing `StrictOptimizedSeqOps`…

Add StrictOptimizedSeqOps

---

src/main/scala/strawman/collection/Factories.scala
src/main/scala/strawman/collection/Iterable.scala
src/main/scala/strawman/collection/SortedMap.scala
src/main/scala/strawman/collection/SortedOps.scala
src/main/scala/strawman/collection/SortedSet.scala
src/test/scala/strawman/collection/test/GenericTest.scala
src/test/scala/strawman/collection/test/TraverseTest.scala

Fixes #139.
The approach is to provide not just implicit `BuildFrom` instances but implicit `FromSpecificIterable` instances (which have a `newBuilder()` method that takes no initial collection).
However this solution raises a ambiguous implicits error when used with sorted Map collections (e.g. `TreeMap`). But I believe this is a limitation of the current way we prioritize implicits. See my comments in the diff for more details.

Implicit factories

---

README.md
src/main/scala/strawman/collection/Iterable.scala
src/main/scala/strawman/collection/immutable/List.scala
src/main/scala/strawman/collection/mutable/ListBuffer.scala

Also add `prependAll` (`++:`) operation.
Fixes #162.

Port List optimizations to the strawman.

---

src/main/scala/strawman/collection/Iterator.scala
src/main/scala/strawman/collection/mutable/HashMap.scala
src/main/scala/strawman/collection/mutable/HashTable.scala

This PR adds several missing operations on `Iterator`, improves the implementation of its `concat` method, and fixes the implementation of the `getOrElseUpdate` method in `mutable.HashMap`.

Fixes, performance and usability improvements

---

src/main/scala/strawman/collection/ArrayOps.scala
src/main/scala/strawman/collection/BitSet.scala
src/main/scala/strawman/collection/Iterable.scala
src/main/scala/strawman/collection/LinearSeq.scala
src/main/scala/strawman/collection/Map.scala
src/main/scala/strawman/collection/Seq.scala
src/main/scala/strawman/collection/Set.scala
src/main/scala/strawman/collection/SortedMap.scala
src/main/scala/strawman/collection/SortedSet.scala
src/main/scala/strawman/collection/StrictOptimizedIterableOps.scala
src/main/scala/strawman/collection/StrictOptimizedSeqOps.scala
src/main/scala/strawman/collection/StringOps.scala
src/main/scala/strawman/collection/View.scala
src/main/scala/strawman/collection/immutable/ImmutableArray.scala
src/main/scala/strawman/collection/immutable/Map.scala
src/main/scala/strawman/collection/immutable/Seq.scala
src/main/scala/strawman/collection/immutable/Set.scala
src/main/scala/strawman/collection/immutable/SortedMap.scala
src/main/scala/strawman/collection/immutable/SortedSet.scala
src/main/scala/strawman/collection/immutable/StrictOptimizedSeqOps.scala
src/main/scala/strawman/collection/mutable/Map.scala
src/main/scala/strawman/collection/mutable/Set.scala
src/main/scala/strawman/collection/mutable/SortedMap.scala
src/main/scala/strawman/collection/mutable/SortedSet.scala

This PR extracts the changes performed in #173 that are unrelated with `withFilter`, and polishes them.
For more details, see [this comment](https://github.com/scala/collection-strawman/pull/173#discussion_r129514133):
> I add [a `coll: C`] member to `IterableOps[A, CC[_], C]`. Why is it useful? In this PR it’s needed by `WithFilter`, which uses a `BuildFrom` instance to build the result of `map` and `flatMap`, and `BuildFrom` needs an initial collection `C` to create a builder.
> 
> Note, that this member was previously already existing in `SeqOps`. It was needed because `SeqOps` is extended by (at least) `StringOps` and `List`, and to implement methods of `SeqOps` we sometimes needed a `C` (ie. `String` or `List[A]`) value and sometimes an `Iterable[A]` (ie. `StringView` or `List[A]`) …

Distinction between collection type C and Iterable[A]

---

src/main/scala/strawman/collection/Map.scala

This is a workaround to avoid https://github.com/lampepfl/dotty/issues/2944 when recompiling the strawman from TASTY.

Workaround to avoid bug on bindings in Tasty

---

benchmarks/time/src/main/scala/strawman/collection/immutable/HashSetBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/immutable/ScalaHashSetBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/immutable/ScalaTreeSetBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/immutable/TreeSetBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/mutable/ScalaArrayBenchmark.scala
project/Bencharts.scala

The issue in #163 is that potentially zero values are being plotted in a logarithmic axis (the logarithm of zero is undefined/infinity). The `org.jfree.chart.axis.LogAxis` class does not seem to allow zero/negative values (see impl. of `setSmallestValue`) or accepts them silently and the result is a messed up chart like the one below:
I have thought of a few options to solve this:
1. **remove zeroes:** I don't think we want this as zero is a valid input size for the benchmarks
2. **replace zeroes with a very small positive number (cheating):** the chart is still messed up if the number is too small.
3. **use a linear axis instead:** this one would plot the zeroes. However, if there is a large range of input values (as is the case for HashSetBenchmark) the ones at the beginning would be …

#163 Fix incorrect benchmarks charts

---

src/main/scala/strawman/collection/View.scala

I copied the comment from 2.12.3's documentation, which is accurate for strawman also.

Fix the comment for `fill`.

---

src/main/scala/strawman/collection/BuildFrom.scala
src/main/scala/strawman/collection/Factories.scala
src/main/scala/strawman/collection/Factory.scala
src/main/scala/strawman/collection/Iterable.scala
src/main/scala/strawman/collection/Iterator.scala
src/test/scala/strawman/collection/test/GenericTest.scala
src/test/scala/strawman/collection/test/TraverseTest.scala
test/junit/src/test/scala/strawman/collection/FactoriesTest.scala

Fixes #198
These changes re-introduce the `BuildFrom` behaviour as it was before #168: the dynamic factory of the source collection is reused to build the target collection.
The PR contains several commits. The [first one](https://github.com/scala/collection-strawman/pull/249/commits/b7195c5704c75f3c5ed26627b3d608e9adbb23b5) contains the essence of the fix and the second one only performs renamings (`CanBuild` is renamed to `Factory`, and `BuildFrom` is moved to a separate file). I suggest to review the first commit before looking at the rest.
Last, I also pushed an alternative implementation [here](https://github.com/julienrf/collection-strawman/commit/d2cfa497fbab6612eceb7b4a32ab089f58fd8227) that makes the conversion between factories and `BuildFrom` instances explicit. I explained the …

Separate BuildFrom and CanBuild.

---

benchmarks/time/src/main/scala/strawman/collection/GroupMapBenchmarks.scala
collections/src/main/scala/strawman/collection/Iterable.scala
test/junit/src/test/scala/strawman/collection/IterableTest.scala

Fixes #42 
I think we should put these methods (at least `groupMap`) into the core rather than collections-contrib because these methods have been well received by the community in my recent [poll](https://contributors.scala-lang.org/t/which-operations-should-be-included-in-the-new-collections): highest rate of accept, no strong reject.
Here are the benchmarks showing a 2x speedup (blue line) over the manual equivalent (using `mapValues`). The benchmark consists in creating a `List` of 10000 elements and then calling `groupMap` or `groupMapReduce` on it. The `size` axis shows the size of the _groups_, not the collection.
JMH report:
~~~
[info] Benchmark                                          (size)  Mode  Cnt       Score        Error  Units
[info] GroupMapBenchmark.groupMap …

Add groupMap and groupMapReduce operations on Iterable

---

collections/src/main/scala/strawman/collection/immutable/List.scala
test/junit/src/test/scala/strawman/collection/immutable/ListTest.scala

Don’t recompute the shared tail.
Fixes #256 
Benchmark on call to `updated` with random indices, for various sizes of lists (lower is better):
The `ListUpdatedBenchmark` line (in blue) contains the specialized implementation.

Optimize List#updated

---

collections/src/main/scala/strawman/collection/Map.scala
collections/src/main/scala/strawman/collection/Seq.scala
collections/src/main/scala/strawman/collection/Set.scala
collections/src/test/scala/strawman/collection/test/Test.scala
test/junit/src/test/scala/strawman/collection/EqualityTest.scala

They were previously in the collection Ops class but it doesn’t
make sense to have them there because the Ops classes can be
inherited by Views, which must always use reference
equality and hashcode.

Move equality implementations into collection classes

---

collections-contrib/src/main/scala/strawman/collection/decorators/ImmutableMapDecorator.scala
collections-contrib/src/main/scala/strawman/collection/decorators/MutableMapDecorator.scala
collections-contrib/src/main/scala/strawman/collection/decorators/package.scala
collections-contrib/src/test/scala/strawman/collection/decorators/ImmutableMapDecoratorTest.scala
collections-contrib/src/test/scala/strawman/collection/decorators/MutableMapDecoratorTest.scala

Fixes #251. Adds an `updateWith` method to mutable Maps and an `updatedWith` method to immutable Maps.

Add updateWith/updatedWith methods to Map collections

---

benchmarks/time/src/main/scala/strawman/collection/immutable/ListFillBenchmarks.scala
collections/src/main/scala/strawman/collection/Factory.scala
collections/src/main/scala/strawman/collection/immutable/ImmutableArray.scala
collections/src/main/scala/strawman/collection/immutable/List.scala
collections/src/main/scala/strawman/collection/immutable/Vector.scala
collections/src/main/scala/strawman/collection/mutable/ArrayBuffer.scala
collections/src/main/scala/strawman/collection/mutable/ListBuffer.scala

Fixes #232.
I’m copying here the comment I’ve posted [there](https://github.com/scala/collection-strawman/issues/233#issuecomment-337634804) explaining what I’ve done:
I’ve run the benchmark given in #232 and we effectively are between 2x to 20x slower than the current collections. Here are the detailed result:
~~~
[info] Benchmark                      (size)  Mode  Cnt         Score          Error  Units
[info] ListFillBenchmarks.fill             0  avgt    8        63.071 ±       16.316  ns/op
[info] ListFillBenchmarks.fill             1  avgt    8        62.975 ±        1.338  ns/op
[info] ListFillBenchmarks.fill             2  avgt    8        70.110 ±        0.903  ns/op
[info] ListFillBenchmarks.fill             3  avgt    8        76.061 ±        0.617  ns/op
[info] …

Optimize Seq factory methods.

---

collections/src/main/scala/strawman/collection/JavaConverters.scala
collections/src/main/scala/strawman/collection/convert/AsJavaConverters.scala
collections/src/main/scala/strawman/collection/convert/AsScalaConverters.scala
collections/src/main/scala/strawman/collection/convert/DecorateAsJava.scala
collections/src/main/scala/strawman/collection/convert/DecorateAsScala.scala
collections/src/main/scala/strawman/collection/convert/Decorators.scala
collections/src/main/scala/strawman/collection/convert/WrapAsJava.scala
collections/src/main/scala/strawman/collection/convert/WrapAsScala.scala
collections/src/main/scala/strawman/collection/convert/Wrappers.scala
test/junit/src/test/scala/strawman/collection/convert/MapWrapperTest.scala
test/junit/src/test/scala/strawman/collection/convert/NullSafetyToJavaTest.scala
test/junit/src/test/scala/strawman/collection/convert/NullSafetyToScalaTest.scala
test/junit/src/test/scala/strawman/collection/convert/WrapperSerializationTest.scala

Pretty much 1:1 from the current 2.12/2.13 impl. Deprecated parts only when necessary to implement the non-deprecated ones.

Add back the non-deprecated Java collection converter APIs

---

collections/src/main/scala/strawman/collection/convert/AsJavaConverters.scala
collections/src/main/scala/strawman/collection/convert/AsScalaConverters.scala
collections/src/main/scala/strawman/collection/convert/DecorateAsJava.scala
collections/src/main/scala/strawman/collection/convert/DecorateAsScala.scala
collections/src/main/scala/strawman/collection/convert/WrapAsJava.scala
collections/src/main/scala/strawman/collection/convert/WrapAsScala.scala
collections/src/main/scala/strawman/collection/convert/Wrappers.scala

Here's the `concurrent.Map` support that was still missing in #279

Enable Java converters for concurrent maps

---

scalafix/output/src/main/scala/fix/Collectionstrawman_v0.scala
scalafix/rewrites/src/main/scala/fix/Collectionstrawman_v0.scala

There are two scalafix tests failing:
- scala/fix/Collectionstrawman_v0_Traversable.scala:
```
[info]   =======
[info]   => Diff
[info]   =======
[info]        xs.to(strawman.collection.Map)
[info]   -    xs.iterator
[info]   +    xs.iterator()
```
`scala.collection.TraversableLike.toIterator` was being converted to `iterable` without `()`
- scala/fix/Collectionstrawman_v0.scala:
```
[info]   =======
[info]   => Diff
[info]   =======
[info]   -import scala.Predef.{ augmentString => _, intArrayOps => _, wrapString => _, _ }
[info]   +import scala.Predef.{ augmentString => _, genericArrayOps => _, genericWrapArray => _, intArrayOps => _, wrapIntArray => _, wrapString => _, _ }
```
Here some unimports from Predef were not being added to the resulting file (`genericArrayOps`, …

Fix broken scalafix tests

---

CONTRIBUTING.md
scalafix/build.sbt
scalafix/input/src/main/scala/fix/Collectionstrawman_v0.scala
scalafix/input/src/main/scala/fix/Collectionstrawman_v0_Traversable.scala
scalafix/input/src/main/scala/fix/ListTest.scala
scalafix/project/plugins.sbt
scalafix/rules/src/main/scala/fix/Collectionstrawman_v0.scala
scalafix/tests/src/test/scala/fix/Collectionstrawman_Tests.scala

Upgrading Scalafix from `0.5.0-M4` to `0.5.3`. There were [breaking changes in `0.5.0-RC3`](https://github.com/scalacenter/scalafix/releases/tag/v0.5.0-RC3) as well as in [Scalameta `2.0`](https://github.com/scalameta/scalameta/blob/15a0187501dc8e5a6fe06d0e002ce1d3340968dc/changelog/2.0.0.md#breaking-changes). 
/cc @olafurpg

Upgrade Scalafix to latest (0.5.3)

---

collections/src/main/scala/strawman/collection/IterableOnce.scala

Since now the `from` factory method accept an `IterableOnce` we don’t need to check whether the receiver is actually an `Iterable` or not.
We could even make these `toXxx` methods available (without deprecation) on `IterableOnce`. What do you think?

Simplify toXxx methods on IterableOnce

---

scalafix/input/src/main/scala/fix/Collectionstrawman_v0_TupleNZipped.scala
scalafix/output/src/main/scala/fix/Collectionstrawman_v0_TupleNZipped.scala
scalafix/rules/src/main/scala/fix/Collectionstrawman_v0.scala

Enhancing the scalafix rule to rewrite `(xs, ys).zipped` to `xs.lazyZip(ys)` (likewise for triples).
There is one caveat here: `LazyZipN.filter` [is not equivalent to](https://github.com/scala/collection-strawman/pull/223#issuecomment-336372816) `TupleNZipped.filter`. This will likely require manual intervention to be fully fixed. Choosing not to rewrite `(xs, ys).zipped.filter(p)` would leave it in a broken state anyway because a `TupleNZipped` cannot be created with iterables from strawman.
/cc @olafurpg

Scalafix rewrite for lazyZip

---

collections-contrib/src/main/scala/strawman/collection/decorators/IterableDecorator.scala
collections-contrib/src/main/scala/strawman/collection/decorators/IteratorDecorator.scala
collections-contrib/src/main/scala/strawman/collection/decorators/package.scala
collections-contrib/src/test/scala/strawman/collection/decorators/IterableDecoratorTest.scala
collections/src/main/scala/strawman/collection/Iterable.scala
collections/src/main/scala/strawman/collection/Iterator.scala
test/junit/src/test/scala/strawman/collection/IteratorTest.scala

Fixes #107 and #186. Based on #228 and #225, rebased, squashed and moved to collections-contrib. I removed `foldSomeRight` (I only kept `foldSomeLeft` and `lazyFoldRight`).

Make foldSomeLeft and lazyFoldRight decorators

---

collections/src/main/scala/strawman/collection/immutable/HashMap.scala
collections/src/main/scala/strawman/collection/immutable/List.scala

...and put them on the subclasses, out of an abundance of caution.
Starting in 2.13.0-M3, the `serialVersionUID` field is emitted as `private`, and so won't be applied to `trait`s, which can't have `private` members. The value didn't have an effect on the Java serialization algorithm, so this changes nothing.
Also, compute the serialVersionUID value for the subtypes of those traits, since evidently it was intended that they have a stable value.
Fixes #296.

Remove @SerialVersionUID from traits.

---

collections/src/main/scala/strawman/collection/mutable/TreeMap.scala
collections/src/main/scala/strawman/collection/mutable/TreeSet.scala
test/scalacheck/src/test/scala/strawman/collection/mutable/MutableTreeMap.scala
test/scalacheck/src/test/scala/strawman/collection/mutable/MutableTreeSet.scala

Fix #301. 
There is one thing I am not so sure. I didn't rename values' name that declares in each test. For example, I still kept `mapView` instead of `mapProjection`. As far as I know, those two words could be interchange. If it's better to keep the same suffix for values' name in each test, please let me know. Thanks! :)

Rename TreeMapView and TreeSetView to avoid confusion with Views.

---

README.md
collections-contrib/src/main/scala/strawman/collection/MultiSet.scala
collections-contrib/src/main/scala/strawman/collection/SortedMultiSet.scala
collections-contrib/src/main/scala/strawman/collection/decorators/ImmutableMapDecorator.scala
collections-contrib/src/main/scala/strawman/collection/decorators/package.scala
collections-contrib/src/main/scala/strawman/collection/immutable/MultiSet.scala
collections-contrib/src/main/scala/strawman/collection/immutable/SortedMultiSet.scala
collections-contrib/src/main/scala/strawman/collection/mutable/MultiSet.scala
collections-contrib/src/main/scala/strawman/collection/mutable/SortedMultiSet.scala
collections-contrib/src/test/scala/strawman/collection/MultiSetTest.scala
collections-contrib/src/test/scala/strawman/collection/SortedMultiSetTest.scala
collections-contrib/src/test/scala/strawman/collection/immutable/MultiSetTest.scala
collections-contrib/src/test/scala/strawman/collection/immutable/SortedMultiSetTest.scala
collections-contrib/src/test/scala/strawman/collection/mutable/MultiSetTest.scala
collections-contrib/src/test/scala/strawman/collection/mutable/SortedMultiSetTest.scala
collections/src/main/scala/strawman/collection/mutable/SortedMap.scala

Fixes #133.
Add `MultiSet` (both mutable and immutable), and `SortedMultiSet` (both mutable and immutable).
A `SortedMultiSet` can be used as a `SortedSeq` (since a multiset can contain duplicates). Therefore, this PR is also a solution to #132.
I took a different approach from #263: in this pull request `MultiSet` creates a new branch in the hierarchy (it doesn’t inherit from `Set`).
Here is an overview of the hierarchy and its relation with `Iterable`:
I put everything in the `collections-contrib` project. I don’t think we need these collections in the core.

Add MultiSet and SortedMultiSet

---

scalafix/input/src/main/scala/fix/Collectionstrawman_v0.scala
scalafix/input/src/main/scala/fix/Collectionstrawman_v0_Traversable.scala
scalafix/input/src/main/scala/fix/ConvertersTest.scala
scalafix/output/src/main/scala/fix/Collectionstrawman_v0.scala
scalafix/output/src/main/scala/fix/Collectionstrawman_v0_Traversable.scala
scalafix/output/src/main/scala/fix/ConvertersTest.scala
scalafix/rules/src/main/scala/fix/Collectionstrawman_v0.scala

- Fix the current migration rules to deduplicate unimports (see scalacenter/scalafix#478) ;
- Add a migration rule for “import scala.collection.JavaConverters._”.

Add more migration rules

---

collections/src/main/scala/strawman/collection/ArrayOps.scala
collections/src/main/scala/strawman/collection/IndexedSeq.scala
collections/src/main/scala/strawman/collection/LinearSeq.scala
collections/src/main/scala/strawman/collection/Seq.scala
collections/src/main/scala/strawman/collection/StringOps.scala
collections/src/main/scala/strawman/collection/immutable/HashMap.scala
collections/src/main/scala/strawman/collection/immutable/ImmutableArray.scala
collections/src/main/scala/strawman/collection/immutable/List.scala
collections/src/main/scala/strawman/collection/immutable/NumericRange.scala
collections/src/main/scala/strawman/collection/immutable/Range.scala
collections/src/main/scala/strawman/collection/immutable/Vector.scala
collections/src/main/scala/strawman/collection/mutable/ArrayBuffer.scala
collections/src/main/scala/strawman/collection/mutable/ListBuffer.scala

Fixes #290.
The implementation of `size` was O(n) in `Vector` instead of O(1) (only `length` was O(1)), which was at the origin of the severe regression observed in #290.
I fixed that by making `size` a `final` forwarder to `length`. We could also remove `length` at all, as suggested in #147, however I found convenient to have `length` as an abstract member in `Indexed` collections so that I couldn’t forget to implement it.
I will post the benchmark results as soon as they have finished to run… (so, not before tomorrow…)

Fix inconsistencies between size and length implementations

---

collections/src/main/scala/strawman/collection/DefaultMap.scala
collections/src/main/scala/strawman/collection/generic/BitOperations.scala
collections/src/main/scala/strawman/collection/immutable/IntMap.scala
collections/src/main/scala/strawman/collection/immutable/LongMap.scala
collections/src/main/scala/strawman/collection/mutable/AnyRefMap.scala
collections/src/main/scala/strawman/collection/mutable/LongMap.scala
collections/src/main/scala/strawman/collection/mutable/Map.scala
collections/src/main/scala/strawman/collection/mutable/WeakHashMap.scala
test/junit/src/test/scala/strawman/collection/mutable/AnyRefMapTest.scala

This is another big chunk of my scala-integration branch that contains some of the more exotic `Map` types from Scala 2.12. They are all used in the compiler codebase.

Various Map implementations ported from Scala 2.12

---

collections/src/main/scala/strawman/collection/immutable/WrappedString.scala
collections/src/main/scala/strawman/collection/package.scala

The motivation is the same as for Arrays which were originally
wrapped in ArrayView but we later changed it back to WrappedArray
(and ImmutableArray): It is very convenient to have an implicit
conversion of a String to a Seq[Char] but a View is no longer a Seq
in the new collection library.

Bring back WrappedString

---

collections/src/main/scala/strawman/collection/BitSet.scala
collections/src/main/scala/strawman/collection/Factory.scala
collections/src/main/scala/strawman/collection/StringOps.scala
collections/src/main/scala/strawman/collection/immutable/LazyList.scala

I’ve started with the `collection.BitSet` object and then found a couple other issues. I’ve added commits that address them.
In summary, this PR:
- Adds the `collection.BitSet` object (like in the current collections),
- Adds an overload for the `updated` operation on `StringOps`,
- Pulls up the `fill` and `tabulate` operations from `SeqFactory` to `IterableFactoryLike`. The `fill` method makes no sense on `Set` collections but … we have it in 2.12, so it’s simpler to just keep it…
- Adds an `append` alias for the `lazyAppendAll` in `LazyList`.

Add collection.BitSet factory object (and other cross-compatibility improvements)

---

.travis.yml

Currently the CI doesn’t compile the code with Dotty. This PR fixes this issue.

Make sure the code is compiled by Dotty

---

collections/src/main/scala/strawman/collection/IterableOnce.scala
collections/src/main/scala/strawman/collection/Map.scala

When cross-compiling better-files I noticed a few things that were missing:
- an overload of `collect` returning a `Map` in `MapOps`,
- deprecated `toIterator` operation in `IterableOnce`.

Some more things to improve backward compatibility

---

collections/src/main/scala/strawman/collection/mutable/ListBuffer.scala
test/junit/src/test/scala/strawman/collection/mutable/ListBufferTest.scala

Fix clear operation in ListBuffer

---

collections/src/main/scala/strawman/collection/BuildFrom.scala

```
scala> class Lst[+A] {
|   def map[B, That](f: A => B)(implicit bf: strawman.collection.BuildFrom[Lst[A], B, That]): That = scala.Predef.???
| }
defined class Lst
scala> object Test {
|   def foo(l: Lst[scala.Int]) = l.map[scala.Int, Lst[scala.Predef.String]](x => 1)
| }
def foo(l: Lst[scala.Int]) = l.map[scala.Int, Lst[scala.Predef.String]](x => 1)
^
On line 2: error: Cannot construct a collection of type Lst[String] with elements of type Int based on a collection of type Lst[Int].
```
This is an existing test case in scala/scala: https://github.com/scala/scala/blob/2.13.x/test/files/neg/t2462a.check

implicitNotFound for BuildFrom

---

collections/src/main/scala/strawman/collection/mutable/Cloneable.scala
collections/src/main/scala/strawman/collection/mutable/Map.scala
collections/src/main/scala/strawman/collection/mutable/Seq.scala
collections/src/main/scala/strawman/collection/mutable/Set.scala

Introduce Cloneable trait

---

collections/src/main/scala/strawman/collection/BuildFrom.scala
collections/src/main/scala/strawman/collection/Factory.scala
test/junit/src/test/scala/strawman/collection/BuildFromTest.scala
test/junit/src/test/scala/strawman/collection/FactoriesTest.scala

Fixes #363.
~~~
scala> import strawman.collection.{ Factory, BuildFrom }
import strawman.collection.{Factory, BuildFrom}
scala> implicitly[Factory[Char, String]]
res0: strawman.collection.Factory[Char,String] = strawman.collection.Factory$$anon$1@b2b85c1
scala> implicitly[Factory[Char, Array[Char]]]
res1: strawman.collection.Factory[Char,Array[Char]] = strawman.collection.Factory$$anon$2@3f9fad3c
scala> implicitly[BuildFrom[String, Char, String]]
res2: strawman.collection.BuildFrom[String,Char,String] = strawman.collection.BuildFrom$$anon$4@14687755
scala> implicitly[BuildFrom[Array[Int], Char, Array[Char]]]
res3: strawman.collection.BuildFrom[Array[Int],Char,Array[Char]] = strawman.collection.BuildFrom$$anon$5@4d7234de
~~~

Add Factory and BuildFrom instances for String and Array

---

collections/src/main/scala/strawman/collection/IndexedSeq.scala
collections/src/main/scala/strawman/collection/Iterable.scala
collections/src/main/scala/strawman/collection/Searching.scala
collections/src/main/scala/strawman/collection/Seq.scala
collections/src/main/scala/strawman/collection/generic/IsIterableLike.scala
collections/src/main/scala/strawman/collection/generic/IsSeqLike.scala

It is not clear from https://github.com/scala/scala/pull/903 why these
methods were not added directly to the collection classes, so that is
what I’m doing here.
`Searching` still exists and contains `SearchResult` and its subtypes.
We should consider moving `SearchResult` directly into the package
and `Found` and `InsertionPoint` into its companion object.

Add search methods from scala.collection.Searching

---

collections/src/main/scala/strawman/collection/immutable/LazyList.scala
collections/src/test/scala/strawman/collection/test/Test.scala
test/junit/src/test/scala/strawman/collection/immutable/LazyListTest.scala
test/junit/src/test/scala/strawman/collection/immutable/StreamTest.scala

Since the semantics are subtly different we should add a deprecated `Stream` with the expected semantics rather than aliasing to `LazyList`

Generalize LazyList to allow implementation of Stream

---

collections/src/main/scala/strawman/collection/convert/ImplicitConversions.scala
collections/src/main/scala/strawman/collection/convert/Wrappers.scala
test/junit/src/test/scala/strawman/collection/convert/JCollectionWrapperTest.scala
test/junit/src/test/scala/strawman/collection/convert/JIterableWrapperTest.scala
test/junit/src/test/scala/strawman/collection/convert/JListWrapperTest.scala
test/junit/src/test/scala/strawman/collection/convert/JSetWrapperTest.scala

This PR addresses #372 and fixes `StackOverflowError`s found in Java wrappers' iterator() while testing.

Bring back collection.convert.ImplicitConversions and fix StackOverflowError in Java wrappers' iterator()

---

collections/src/main/scala/strawman/collection/Factory.scala
collections/src/main/scala/strawman/collection/Iterator.scala
collections/src/main/scala/strawman/collection/immutable/ImmutableArray.scala
collections/src/main/scala/strawman/collection/immutable/WrappedString.scala
collections/src/main/scala/strawman/collection/mutable/WrappedArray.scala
collections/src/main/scala/strawman/collection/package.scala
test/junit/src/test/scala/strawman/collection/FactoriesTest.scala

This reinstates the factory part of the abstraction for arbitrary
evidence type constructors which we previously abandoned in favor of
SortedIterableFactory. Now we have a good reason for an
EvidenceIterableFactory with several Ordering-based and several
ClassTag-based factory instances.
ImmutableArray and WrappedArray now have a ClassTag-based factory in
their companion object so that building unboxed arrays with a proper
element type is always the default (and used automatically in calls like
`xs.to(ImmutableArray)` which would previously go through the regular
IterableFactory and build a boxed representation). IterableFactories are
still available as `{ImmutableArray/WrappedArray}.untagged`.
There are no new abstractions at the collection level. We could
consider reintroducing a …

First-class treatment of ClassTag-based factories

---

collections/src/main/scala/strawman/collection/immutable/TreeSet.scala
collections/src/main/scala/strawman/collection/mutable/FlatHashTable.scala
collections/src/main/scala/strawman/collection/mutable/HashMap.scala
collections/src/main/scala/strawman/collection/mutable/HashSet.scala
collections/src/main/scala/strawman/collection/mutable/HashTable.scala
collections/src/main/scala/strawman/collection/mutable/LinkedHashMap.scala
collections/src/main/scala/strawman/collection/mutable/LinkedHashSet.scala
test/junit/src/test/scala/strawman/collection/immutable/SerializationTest.scala
test/junit/src/test/scala/strawman/collection/mutable/SerializationTest.scala

Fix serialization issues in HashMap, LinkedHashMap, HashSet and LinkedHashSet

---

benchmarks/time/src/main/scala/strawman/collection/immutable/ChampHashSetBenchmark.scala
benchmarks/time/src/main/scala/strawman/collection/immutable/HashSetBenchmark.scala
build.sbt
collections/src/main/scala/strawman/collection/immutable/ChampCommon.scala
collections/src/main/scala/strawman/collection/immutable/ChampHashMap.scala
collections/src/main/scala/strawman/collection/immutable/ChampHashSet.scala
collections/src/main/scala/strawman/collection/immutable/Map.scala
collections/src/main/scala/strawman/collection/immutable/Set.scala
test/junit/src/test/scala/strawman/collection/immutable/ChampMapSmokeTest.scala
test/junit/src/test/scala/strawman/collection/immutable/ChampSetSmokeTest.scala
test/junit/src/test/scala/strawman/collection/immutable/CustomHashInt.scala
test/scalacheck/src/test/scala/strawman/collection/Generators.scala
test/scalacheck/src/test/scala/strawman/collection/immutable/ImmutableChampHashMapProperties.scala
test/scalacheck/src/test/scala/strawman/collection/immutable/ImmutableChampHashSetProperties.scala

This pull request contains reimplementations of immutable `HashSet` and `HashMap` using [Compressed Hash-Array Mapped Prefix-trees (CHAMP)](https://michael.steindorfer.name/publications/oopsla15.pdf). A prototype and preliminary evaluation of CHAMP data structures in collection-strawman was already discussed in issue #192.
The new implementations (`ChampHashSet` and `ChampHashMap`) currently exist next to the `HashMap` and `HashSet`. By default `immutable.Map` and `immutable.Set` now pickup the CHAMP versions, but I also implemented a JVM flag (`-Dstrawman.collection.immutable.useBaseline=true`) to default to the current `HashSet` and `HashMap` implementations. I assume that in the final version of the collections only one hash-map/set will ship, but for now, having a flag helps with …

New immutable hash set and map

---

collections/src/main/scala/strawman/collection/LinearSeq.scala
collections/src/main/scala/strawman/collection/immutable/List.scala
test/junit/src/test/scala/strawman/collection/immutable/LazyListTest.scala

Fixes #395
- Add extra condition in `LinearSeq.drop` to stop recursion when `tail` is empty (seemed pointless).
- Remove override in `List` as it basically duplicates what `LinearSeq.drop` does now

Make LazyList.drop safe

---

collections/src/main/scala/strawman/collection/immutable/Vector.scala
test/junit/src/test/scala/strawman/collection/immutable/VectorTest.scala

This PR aims to fix #399
`Vector` provides an optimized version of `prependedAll` (overrides the one inherited from `StrictOptimizedSeqOps`). In one of the cases, the `prefix` elements are incorrectly stacked in front of `this`, which messes up with the order of the resulting vector.
My solution to this was to relax the visibility of `Iterable.reversed` as it seemed to be the fastest alternative to have the elements prepended in the correct order.
I ran some [benchmarks](https://gist.github.com/marcelocenerine/0bac34b3c9def261cd5029a874b4d4ae) to compare the performance of:
- Scala's `Vector.++:`
- `prependedAll` inherited from `StrictOptimizedSeqOps`
- the buggy `prependedAll`
- the fixed `prependedAll`
It turns out that the optimization for `Vector` is ~5x faster than the one from …

Fix Vector.prependedAll

---

collections/src/main/scala/strawman/collection/mutable/ArrayBuffer.scala
collections/src/main/scala/strawman/collection/mutable/Buffer.scala
collections/src/main/scala/strawman/collection/mutable/ListBuffer.scala
test/junit/src/test/scala/strawman/collection/mutable/ArrayBufferTest.scala
test/junit/src/test/scala/strawman/collection/mutable/ListBufferTest.scala

This PR fixes #413, #409, #410, #406
My original goal was to fix #413 only. It turns out that I had to fix other bugs along the way to allow the original one to be fixed or was somehow related. Some of these bugs have issues and others don't (e.g. `ListBuffer.remove(idx)`, `Buffer.trimStart/trimEnd`, ...). Each fix is in a separate commit to ease the code review
There are still some bugs in those classes which are covered by other issues that @Ichoran has already filed

Bug fixes for Buffer/ArrayBuffer/ListBuffer

---

collections/src/main/scala/strawman/collection/mutable/LinkedList.scala
collections/src/main/scala/strawman/collection/mutable/MutableList.scala
collections/src/main/scala/strawman/collection/mutable/Queue.scala

This includes mutable.LinkedList and mutable.MutableList. They were
already deprecated in 2.12 and are now package-private. We should
consider simplifying the implementation of Queue so that they can be
removed entirely in the future.

A port of mutable.Queue from the old collections

---

collections/src/main/scala/strawman/collection/generic/package.scala

That would allow a small subset of existing code to be source compatible with the new collections.
Typically, the following will cross compile:
~~~ scala
def foo[F[_], A, T](from: F[A])(implicit cbf: CanBuildFrom[F[A], A, T]) = {
val builder = cbf(from)
…
builder.result
}
~~~
(Unfortunately, my guess is that most usages of `CanBuildFrom` will require adaptation, but at least that one would be compatible…)

Add deprecated CanBuildFrom alias to BuildFrom

---

collections/src/main/scala/strawman/collection/ArrayOps.scala
collections/src/main/scala/strawman/collection/IndexedSeq.scala
collections/src/main/scala/strawman/collection/Iterator.scala
collections/src/main/scala/strawman/collection/LinearSeq.scala
collections/src/main/scala/strawman/collection/Seq.scala
collections/src/main/scala/strawman/collection/StringOps.scala
collections/src/main/scala/strawman/collection/View.scala
collections/src/main/scala/strawman/collection/convert/Wrappers.scala
collections/src/main/scala/strawman/collection/immutable/ImmutableArray.scala
collections/src/main/scala/strawman/collection/immutable/NumericRange.scala
collections/src/main/scala/strawman/collection/immutable/Range.scala
collections/src/main/scala/strawman/collection/immutable/TrieIterator.scala
collections/src/main/scala/strawman/collection/immutable/Vector.scala
collections/src/main/scala/strawman/collection/immutable/WrappedString.scala
collections/src/main/scala/strawman/collection/mutable/ArrayBuffer.scala
collections/src/main/scala/strawman/collection/mutable/ArrayBuilder.scala
collections/src/main/scala/strawman/collection/mutable/Buffer.scala
collections/src/main/scala/strawman/collection/mutable/Builder.scala
collections/src/main/scala/strawman/collection/mutable/ListBuffer.scala
collections/src/main/scala/strawman/collection/mutable/UnrolledBuffer.scala
collections/src/main/scala/strawman/collection/mutable/WrappedArray.scala

Fixes #147.
The idea is to offer to users only one way to get the size of a collection: the `size` operation. Therefore, `length` is deprecated and `final` (it just calls `size`).
That being said, I found it convenient for indexed collections to have an abstract method giving the size so that implementors *have to* implement it instead of having to *remember* of overriding the `size` operation (whose default implementation is O(n)). Previously, indexed collections were using the `length` method in that way. I replaced it with a protected `finiteSize` method.

Standardize on .size (but still offer .length)

---

collections/src/main/scala/strawman/collection/View.scala
collections/src/main/scala/strawman/collection/mutable/ArrayBuffer.scala
collections/src/main/scala/strawman/collection/mutable/Buffer.scala
collections/src/main/scala/strawman/collection/mutable/ListBuffer.scala
test/junit/src/test/scala/strawman/collection/mutable/ArrayBufferTest.scala
test/junit/src/test/scala/strawman/collection/mutable/ListBufferTest.scala

- fix #398 (`Buffer.patch` throws out of bound index exception) by dropping validation in `View.Patched`
- fix #407 (`ListBuffer.patchInPlace` throws class cast exception) by clipping index/count to safe values
- fix various issues in `ArrayBuffer.patchInPlace` causing out of bound index exceptions
- fix #385 (`ArrayBuffer.clear` not dereferencing cleared elements)
- Ensure that index passed into `ArrayBuffer`'s `apply` and `update` is within bounds. This fix uncovered other issues in `addOne` and `insert`
Note: each fix is in a separate commit

Bunch of bug fixes for `ArrayBuffer` & `ListBuffer`

---

collections/src/main/scala/strawman/collection/mutable/ArrayBuffer.scala
collections/src/main/scala/strawman/collection/mutable/PriorityQueue.scala

We don’t have ResizableArray anymore so we use ArrayBuffer instead.
It wasn’t clear to me why PriorityQueue didn’t use ArrayBuffer in the
first place rather than a custom implementation of ResizableQueue.

mutable.PriorityQueue from the old collections

---

collections-contrib/src/main/scala/strawman/collection/mutable/SortedMultiDict.scala
collections/src/main/scala/strawman/collection/Factory.scala
collections/src/main/scala/strawman/collection/Iterable.scala
collections/src/main/scala/strawman/collection/View.scala
collections/src/main/scala/strawman/collection/immutable/IntMap.scala
collections/src/main/scala/strawman/collection/immutable/Map.scala

This allows us to get rid of `IterableFactoryLike` and still define
`View.from` in a reasonable way.
I pushed this branch last week but most have forgotten to open a PR...

Memoize IterableOnce source on first View traversal

---

collections/src/main/scala/strawman/collection/ArrayOps.scala
collections/src/main/scala/strawman/collection/IndexedSeq.scala
collections/src/main/scala/strawman/collection/Iterator.scala
collections/src/main/scala/strawman/collection/LinearSeq.scala
collections/src/main/scala/strawman/collection/Seq.scala
collections/src/main/scala/strawman/collection/StringOps.scala
collections/src/main/scala/strawman/collection/View.scala
collections/src/main/scala/strawman/collection/convert/Wrappers.scala
collections/src/main/scala/strawman/collection/immutable/ImmutableArray.scala
collections/src/main/scala/strawman/collection/immutable/NumericRange.scala
collections/src/main/scala/strawman/collection/immutable/Range.scala
collections/src/main/scala/strawman/collection/immutable/TrieIterator.scala
collections/src/main/scala/strawman/collection/immutable/Vector.scala
collections/src/main/scala/strawman/collection/immutable/WrappedString.scala
collections/src/main/scala/strawman/collection/mutable/ArrayBuffer.scala
collections/src/main/scala/strawman/collection/mutable/ArrayBuilder.scala
collections/src/main/scala/strawman/collection/mutable/Buffer.scala
collections/src/main/scala/strawman/collection/mutable/Builder.scala
collections/src/main/scala/strawman/collection/mutable/LinkedList.scala
collections/src/main/scala/strawman/collection/mutable/ListBuffer.scala
collections/src/main/scala/strawman/collection/mutable/MutableList.scala
collections/src/main/scala/strawman/collection/mutable/UnrolledBuffer.scala
collections/src/main/scala/strawman/collection/mutable/WrappedArray.scala
collections/src/main/scala/strawman/collection/package.scala

This reverts https://github.com/scala/collection-strawman/pull/356 which causes compatibility issues requiring unnecessary changes in every Seq implementation for no obvious benefit.

Revert length / size changes

---

benchmarks/time/src/main/scala/benchmarks/immutableHashSet/package.scala
collections/src/main/scala/strawman/collection/immutable/HashSet.scala

Fixes #380 (I checked it locally but didn’t duplicate the test in our repository).
For some reason when I ported the code of `HashSet` to the new design I only took the minimum amount of code. This PR also takes optimizations from the old collections and put them in the new collections.

Add back optimizations of HashSet

---

collections/src/main/scala/strawman/collection/DefaultMap.scala
collections/src/main/scala/strawman/collection/Map.scala
collections/src/main/scala/strawman/collection/SortedMap.scala
collections/src/main/scala/strawman/collection/concurrent/TrieMap.scala
collections/src/main/scala/strawman/collection/convert/Wrappers.scala
collections/src/main/scala/strawman/collection/immutable/ChampHashMap.scala
collections/src/main/scala/strawman/collection/immutable/HashMap.scala
collections/src/main/scala/strawman/collection/immutable/IntMap.scala
collections/src/main/scala/strawman/collection/immutable/ListMap.scala
collections/src/main/scala/strawman/collection/immutable/LongMap.scala
collections/src/main/scala/strawman/collection/immutable/Map.scala
collections/src/main/scala/strawman/collection/immutable/SortedMap.scala
collections/src/main/scala/strawman/collection/immutable/TreeMap.scala
collections/src/main/scala/strawman/collection/mutable/AnyRefMap.scala
collections/src/main/scala/strawman/collection/mutable/HashMap.scala
collections/src/main/scala/strawman/collection/mutable/LinkedHashMap.scala
collections/src/main/scala/strawman/collection/mutable/ListMap.scala
collections/src/main/scala/strawman/collection/mutable/LongMap.scala
collections/src/main/scala/strawman/collection/mutable/Map.scala
collections/src/main/scala/strawman/collection/mutable/OpenHashMap.scala
collections/src/main/scala/strawman/collection/mutable/SortedMap.scala
collections/src/main/scala/strawman/collection/mutable/TreeMap.scala

The scaladoc comment claims that `mapFromIterable` is “similar to
fromIterable” but that method doesn’t exist (anymore). Unlike
`fromSpecificIterable`, `mapFromIterable` is not specific to the
source element type and therefore can never do more than
`mapFactory.from`. The same goes for `sortedMapFromIterable`.

Remove mapFromIterable and sortedMapFromIterable

---

collections/src/main/scala/strawman/collection/immutable/ImmutableArray.scala
test/junit/src/test/scala/strawman/collection/immutable/ImmutableArrayTest.scala

Fix ImmutableArray slice behavior difference with 2.13 and add test case.
Following code won't throw exception anymore
```
package strawman.collection.immutable
object Test extends App {
val array = ImmutableArray(1, 2, 3)
val newArray = array.slice(1, 5)
println(newArray)
}
```

Fix slice behavior difference of ImmutableArray

---

collections/src/main/scala/strawman/collection/Set.scala
collections/src/main/scala/strawman/collection/immutable/Seq.scala
collections/src/main/scala/strawman/collection/immutable/Set.scala
collections/src/main/scala/strawman/collection/mutable/IndexedSeq.scala
collections/src/main/scala/strawman/collection/mutable/Seq.scala
collections/src/main/scala/strawman/collection/mutable/Set.scala

This points to a soundness bug in the compiler. These errors should be
caught. Omitting a necessary override leads to the expected errors in
some cases but not in all.

Fix the iterableFactory of mutable Sets

---

collections/src/main/scala/strawman/collection/Set.scala
collections/src/main/scala/strawman/collection/SortedMap.scala
collections/src/main/scala/strawman/collection/SortedSet.scala
collections/src/main/scala/strawman/collection/immutable/Set.scala

We need to make Set.+ invariant to get the right (2.12-compatible)
behavior in SortedSet.
The deprecated collection.Map.+ was missing an override in
collection.SortedMap to get the correct result (like it was already
done for the non-deprecated immutable versions).

Make deprecated + work for generic Set and Map

---

collections/src/main/scala/strawman/collection/Iterator.scala

add the bare and separator-only variants of addString to Iterator

---

collections/src/main/scala/strawman/collection/Seq.scala

Reverting a small change I made [here](https://github.com/scala/collection-strawman/pull/444/files#diff-d2679eddf2a5dee23263f82189f93c81). It was not needed for the purpose of that PR (turns out the anonymous class is only used internally) and can slightly increase the running time of `diff` and `intersect`. This is likely caused by the fact that `Map.withDefaultValue` wraps the default value in a function causing an additional dispatch every time a key is missing.

 Override HashMap.default in Seq.occCounts instead of using Map.withDefaultValue

---

collections-contrib/src/main/scala/strawman/collection/immutable/MultiSet.scala
collections-contrib/src/main/scala/strawman/collection/immutable/SortedMultiSet.scala
collections-contrib/src/main/scala/strawman/collection/mutable/MultiSet.scala
collections-contrib/src/main/scala/strawman/collection/mutable/SortedMultiSet.scala
collections/src/main/scala/strawman/collection/Iterable.scala
collections/src/main/scala/strawman/collection/IterableOnce.scala
collections/src/main/scala/strawman/collection/Iterator.scala
collections/src/main/scala/strawman/collection/Seq.scala

Introduce IterableOnceOps as common abstraction for Iterable & Iterator

---

collections/src/main/scala/strawman/collection/ArrayOps.scala
collections/src/main/scala/strawman/collection/concurrent/TrieMap.scala
collections/src/main/scala/strawman/collection/immutable/ImmutableArray.scala
collections/src/main/scala/strawman/collection/immutable/TrieIterator.scala
collections/src/main/scala/strawman/collection/mutable/ArrayBuffer.scala
collections/src/main/scala/strawman/collection/mutable/ArrayBuilder.scala
collections/src/main/scala/strawman/collection/mutable/FlatHashTable.scala
collections/src/main/scala/strawman/collection/mutable/HashTable.scala
collections/src/main/scala/strawman/collection/mutable/WrappedArray.scala
test/junit/src/test/scala/strawman/collection/SetMapConsistencyTest.scala

+ more ArrayOps methods and optimizations
See commit comments for details.

Don't extend collection types in ArrayOps

---

collections/src/main/scala/strawman/collection/convert/Wrappers.scala
test/junit/src/test/scala/strawman/collection/convert/MapWrapperTest.scala

This is a port of https://github.com/scala/scala/pull/6233 , which fixes scala/bug#10663
In the above PR, I also deleted a test (test/files/run/t5880.scala) that was testing for good spread in the (better but incorrect) hashcode implementation. I don't see that same test anywhere in this repo however.

Make MapWrapper.Entry's hashCode conform to the contract in java.util.Map.Entry's documentation

---

collections/src/main/scala/strawman/collection/ArrayOps.scala
collections/src/main/scala/strawman/collection/immutable/ImmutableArray.scala

Now that we have efficient Array operations without wrapping in
ArrayOps we can use them in ImmutableArray

Improve ImmutableArray operations

---

collections/src/main/scala/strawman/collection/BuildFrom.scala
collections/src/main/scala/strawman/collection/Factory.scala
test/junit/src/test/scala/strawman/collection/BuildFromTest.scala
test/junit/src/test/scala/strawman/collection/FactoriesTest.scala

Fixes scala/collection-strawman#438
Also removes a unused implicit conversion from IterableFactory to BuildFrom.

Add implicit BuildFrom and Factory instances for BitSets

---

collections/src/main/scala/strawman/collection/immutable/IntMap.scala
collections/src/main/scala/strawman/collection/immutable/LongMap.scala
collections/src/main/scala/strawman/collection/mutable/AnyRefMap.scala
collections/src/main/scala/strawman/collection/mutable/LongMap.scala

Fixes scala/collection-strawman#403
Most of the operation had already been fixed by @szeiger in the meantime, but a few were missing.

More specific return type for transformation operations of IntMap, LongMap and AnyRefMap

---

collections/src/main/scala/strawman/collection/mutable/ArrayDeque.scala
test/junit/src/test/scala/strawman/collection/mutable/ArrayDequeTest.scala

This also affects subclasses like mutable.Queue.
- Remove unnecessary `from` paramter in `requireBounds`.
- Allow `copyToSlice` directly beyond the end of a target array for a
no-op. This is required to make it work for empty arrays.
- Allow `insert` and `insertAll` directly beyond the end of the
`ArrayDeque` for appending to the end.
- Remove explicit `className` in `ArrayDeque` to have it computed
correctly for subclasses like `Queue`.
Fixes https://github.com/scala/collection-strawman/issues/506

Fix bounds checks, etc. in ArrayDeque

---

collections/src/main/scala/strawman/collection/Iterable.scala
collections/src/main/scala/strawman/collection/Traversable.scala
collections/src/main/scala/strawman/collection/package.scala

It was only there to allow bootstrapping on top of 2.13.0-M3. It is no
longer necessary after https://github.com/scala/scala/pull/6364.

Remove Traversable

---

collections/src/main/scala/strawman/collection/immutable/LazyList.scala
test/junit/src/test/scala/strawman/collection/immutable/LazyListTest.scala
test/junit/src/test/scala/strawman/collection/immutable/StreamTest.scala

Fixes scala/collection-strawman#376
Fixes scala/collection-strawman#420
This is a rebased and squashed version of #446 (authored by @dhanesharole).

Make toString in LazyList consistent with other collections.

---

collections/src/main/scala/strawman/collection/ArrayOps.scala
collections/src/main/scala/strawman/collection/Factory.scala
collections/src/main/scala/strawman/collection/StringOps.scala
collections/src/main/scala/strawman/collection/mutable/AnyRefMap.scala
collections/src/main/scala/strawman/collection/mutable/ArrayDeque.scala
collections/src/main/scala/strawman/collection/mutable/Builder.scala
collections/src/main/scala/strawman/collection/mutable/Queue.scala
collections/src/main/scala/strawman/collection/mutable/Stack.scala
collections/src/main/scala/strawman/collection/mutable/package.scala
test/junit/src/test/scala/strawman/collection/ArrayOpsTest.scala
test/junit/src/test/scala/strawman/collection/BuildFromTest.scala

- Restore `IterableFactory.toBuildFrom` which was erroneously removed
in https://github.com/scala/collection-strawman/pull/495
- Fix `ArrayOps.ReverseIterator`
- More explicit syntax in `AnyRefMap.collect` implementation to make it
compile with and without Predef
- Add a deprecated `front` method to `mutable.Queue`

More fixes from latest rebasing of Scala 2.13.x integration build

---

collections/src/main/scala/strawman/collection/immutable/Set.scala

They all print as “Set” now, like in the old collection library.

Don’t expose Set{1..4} names via className / toString
