scala/collection-strawman

- README.md
Hi, this just adds a README with relevant links since people will be curious.
> add readme with links

- .travis.yml
- build.sbt
- project/build.properties
and use latest Scala and sbt
I already enabled Travis over at
https://travis-ci.org/scala/collection-strawman
> add a basic Travis build

- src/main/scala/strawman/collection/CollectionStrawman6.scala
- src/main/scala/strawman/collection/View.scala
- src/main/scala/strawman/collection/package.scala
- src/test/scala/strawman/collection/test/Test.scala
Also removes the cycle between `Iterator` and `IterableOnce`.
> Make it clearer that the `iterator` method will return a fresh Iterator at each call

- .gitignore
- src/main/scala/strawman/collection/Iterable.scala
- src/main/scala/strawman/collection/IterableOnce.scala
- src/main/scala/strawman/collection/Iterator.scala
- src/main/scala/strawman/collection/Seq.scala
- src/main/scala/strawman/collection/Set.scala
- src/main/scala/strawman/collection/View.scala
- src/main/scala/strawman/collection/immutable/LazyList.scala
- src/main/scala/strawman/collection/mutable/ArrayBuffer.scala
- src/main/scala/strawman/collection/mutable/Builder.scala
- src/main/scala/strawman/collection/mutable/Growable.scala
- src/main/scala/strawman/collection/mutable/Iterator.scala
- src/main/scala/strawman/collection/mutable/ListBuffer.scala
- src/main/scala/strawman/collection/mutable/Seq.scala
- src/main/scala/strawman/collection/mutable/Set.scala
- src/main/scala/strawman/collection/package.scala
- src/test/scala/strawman/collection/test/Test.scala
> [WIP] First version to add mutable collections

- src/main/scala/strawman/collection/BitSet.scala
- src/main/scala/strawman/collection/SortedSet.scala
- src/main/scala/strawman/collection/immutable/BitSet.scala
- src/main/scala/strawman/collection/immutable/SortedSet.scala
- src/main/scala/strawman/collection/mutable/BitSet.scala
- src/main/scala/strawman/collection/mutable/Set.scala
- src/main/scala/strawman/collection/mutable/SortedSet.scala
- src/test/scala/strawman/collection/test/Test.scala
> Sketch mutable and immutable BitSets

- build.sbt
- project/plugins.sbt
Enables support to compile with dotty (thx @liufengyun for the tip)
@julienrf WDYT?
> Add support to compile with dotty

- README.md
- src/main/scala/strawman/collection/BitSet.scala
- src/main/scala/strawman/collection/Iterable.scala
- src/main/scala/strawman/collection/Set.scala
- src/main/scala/strawman/collection/Sorted.scala
- src/main/scala/strawman/collection/SortedSet.scala
- src/main/scala/strawman/collection/immutable/BitSet.scala
- src/main/scala/strawman/collection/immutable/SortedSet.scala
- src/main/scala/strawman/collection/immutable/TreeMap.scala
- src/main/scala/strawman/collection/immutable/TreeSet.scala
- src/main/scala/strawman/collection/mutable/BitSet.scala
No fancy abstraction has been introduced. I mainly followed the design…
> Add BitSet implementation

- README.md
- src/main/scala/strawman/collection/BitSet.scala
- src/main/scala/strawman/collection/Factories.scala
- src/main/scala/strawman/collection/Iterable.scala
- src/main/scala/strawman/collection/Set.scala
- src/main/scala/strawman/collection/SortedSet.scala
- src/main/scala/strawman/collection/immutable/BitSet.scala
- src/main/scala/strawman/collection/immutable/HashMap.scala
- src/main/scala/strawman/collection/immutable/HashSet.scala
- src/main/scala/strawman/collection/immutable/Map.scala
- src/main/scala/strawman/collection/immutable/Set.scala
- src/main/scala/strawman/collection/immutable/TreeSet.scala
- src/main/scala/strawman/collection/mutable/ArrayBuffer.scala
- src/main/scala/strawman/collection/mutable/BitSet.scala
- src/main/scala/strawman/collection/mutable/Builder.scala
- src/main/scala/strawman/collection/mutable/FlatHashTable.scala
- src/main/scala/strawman/collection/mutable/Growable.scala
- src/main/scala/strawman/collection/mutable/GrowableBuilder.scala
- src/main/scala/strawman/collection/mutable/HashSet.scala
- src/main/scala/strawman/collection/mutable/HashTable.scala
- src/main/scala/strawman/collection/mutable/RedBlackTree.scala
- src/main/scala/strawman/collection/mutable/Set.scala
- src/main/scala/strawman/collection/mutable/SortedSet.scala
- src/main/scala/strawman/collection/mutable/TreeSet.scala
- src/main/scala/strawman/collection/package.scala
This PR adds mutable Set collections implementation.
> Mutable sets

- src/main/scala/strawman/collection/Factories.scala
- src/main/scala/strawman/collection/Map.scala
- src/main/scala/strawman/collection/SortedMap.scala
- src/main/scala/strawman/collection/immutable/HashMap.scala
- src/main/scala/strawman/collection/immutable/ListMap.scala
- src/main/scala/strawman/collection/immutable/Map.scala
- src/main/scala/strawman/collection/immutable/SortedMap.scala
- src/main/scala/strawman/collection/immutable/TreeMap.scala
- src/main/scala/strawman/collection/mutable/HashMap.scala
- src/main/scala/strawman/collection/mutable/HashTable.scala
- src/main/scala/strawman/collection/mutable/Iterable.scala
- src/main/scala/strawman/collection/mutable/Map.scala
- src/main/scala/strawman/collection/mutable/SortedMap.scala
- src/main/scala/strawman/collection/mutable/SortedSet.scala
- src/main/scala/strawman/collection/mutable/TreeMap.scala
- src/test/scala/strawman/collection/test/Test.scala
> Add mutable Map collections implementation

- src/main/scala/strawman/collection/immutable/LazyList.scala
- src/test/scala/strawman/collection/test/Test.scala
#79 is fixed by #2435 in the dotty repo. This PR contains the test that failed.
> Fix #79: Add test

- README.md
- benchmarks/memory/src/main/scala/strawman/collection/MemoryFootprint.scala
- benchmarks/time/src/main/scala/strawman/collection/immutable/ImmutableArrayBenchmark.scala
- benchmarks/time/src/main/scala/strawman/collection/immutable/PrimitiveArrayBenchmark.scala
- benchmarks/time/src/main/scala/strawman/collection/immutable/ScalaVectorBenchmark.scala
- src/main/scala/strawman/collection/Seq.scala
- src/main/scala/strawman/collection/immutable/ImmutableArray.scala
- src/main/scala/strawman/collection/immutable/Seq.scala
- src/test/scala/strawman/collection/test/Test.scala
Based on https://github.com/scala/collection-strawman/pull/31, updated
for the new design.
> Support for immutable arrays

- src/main/scala/strawman/collection/mutable/HashTable.scala
See https://github.com/scala/scala/pull/5840 for reference.
> Upper bound on the E type parameter of HashEntry

- README.md
- src/main/scala/strawman/collection/Iterable.scala
- src/main/scala/strawman/collection/Iterator.scala
- src/main/scala/strawman/collection/View.scala
- src/main/scala/strawman/collection/immutable/ImmutableArray.scala
- src/main/scala/strawman/collection/immutable/LazyList.scala
> Add most common operations of Iterable

- src/main/scala/strawman/collection/Seq.scala
- src/main/scala/strawman/collection/immutable/LazyList.scala
- src/main/scala/strawman/collection/immutable/List.scala
- src/test/scala/strawman/collection/test/Test.scala
> Fix LinearSeq length implementation.

- src/main/scala/strawman/collection/immutable/LazyList.scala
- src/main/scala/strawman/collection/immutable/List.scala
- src/main/scala/strawman/collection/immutable/Seq.scala
> Add immutable.LinearSeq, and make List and LazyList extend it.

- src/main/scala/strawman/collection/Factories.scala
- src/main/scala/strawman/collection/IndexedSeq.scala
- src/main/scala/strawman/collection/Iterator.scala
- src/main/scala/strawman/collection/Seq.scala
- src/main/scala/strawman/collection/View.scala
- src/main/scala/strawman/collection/immutable/ImmutableArray.scala
- src/main/scala/strawman/collection/immutable/LazyList.scala
- src/main/scala/strawman/collection/immutable/List.scala
- src/main/scala/strawman/collection/immutable/NumericRange.scala
- src/main/scala/strawman/collection/immutable/Range.scala
- src/main/scala/strawman/collection/immutable/Seq.scala
- src/main/scala/strawman/collection/immutable/Vector.scala
- src/main/scala/strawman/collection/mutable/ArrayBuffer.scala
- src/main/scala/strawman/collection/mutable/ListBuffer.scala
- src/test/scala/strawman/collection/test/FactoriesTest.scala
> Add more factory methods

- CONTRIBUTING.md
- README.md
- scalafix/build.sbt
- scalafix/input/src/main/scala/fix/Collectionstrawman_v0.scala
- scalafix/input/src/main/scala/fix/Collectionstrawman_v0_Traversable.scala
- scalafix/input/src/main/scala/fix/ListTest.scala
- scalafix/output/src/main/scala/fix/Collectionstrawman_v0.scala
- scalafix/output/src/main/scala/fix/Collectionstrawman_v0_Traversable.scala
- scalafix/output/src/main/scala/fix/ListTest.scala
- scalafix/project/build.properties
- scalafix/project/plugins.sbt
- scalafix/readme.md
- scalafix/rewrites/src/main/scala/fix/Collectionstrawman_v0.scala
- scalafix/tests/src/test/scala/fix/Collectionstrawman_Tests.scala
This PR pulls the commits made by @olafurpg on his fork into this repository, and adds more documentation.
> Pull migration tool to this repository

- src/main/scala/strawman/collection/immutable/HashSet.scala
- src/main/scala/strawman/collection/immutable/Map.scala
- src/main/scala/strawman/collection/immutable/Set.scala
- src/main/scala/strawman/collection/immutable/TrieIterator.scala
- test/junit/src/test/scala/strawman/collection/immutable/SetTest.scala
I copied what was done in the standard library.
I’ll post the benchmark results once it’s finished.
@EPronovost I started from your work but finally didn’t keep it because I needed it for `immutable.Set` (instead of `immutable.HashSet`), I’m sorry for the confusion.
> small size specialized implementations of immutable Set and Map

- src/main/scala/strawman/collection/Iterator.scala
> Add Iterator.nextOption

- build.sbt
Updated Dotty to 0.3.0-RC2 as per #227
> Update to Dotty 0.3.0-RC2

- CONTRIBUTING.md
- build.sbt
- documentation/DESIGN.md
- documentation/hierarchy.plantuml
Fixes #196.
I’d be happy to improve it according to the review of _external_ contributors too :)
> Add design documentation

- README.md
- benchmarks/time/src/main/scala/strawman/collection/immutable/ImmutableArrayBenchmark.scala
- benchmarks/time/src/main/scala/strawman/collection/immutable/LazyListBenchmark.scala
- benchmarks/time/src/main/scala/strawman/collection/immutable/ListBenchmark.scala
- benchmarks/time/src/main/scala/strawman/collection/immutable/NumericRangeBenchmark.scala
- benchmarks/time/src/main/scala/strawman/collection/immutable/RangeBenchmark.scala
- benchmarks/time/src/main/scala/strawman/collection/immutable/VectorBenchmark.scala
- benchmarks/time/src/main/scala/strawman/collection/mutable/ArrayBufferBenchmark.scala
- benchmarks/time/src/main/scala/strawman/collection/mutable/ListBufferBenchmark.scala
- src/main/scala/strawman/collection/Iterator.scala
- src/main/scala/strawman/collection/Seq.scala
- src/main/scala/strawman/collection/StrictOptimizedSeqOps.scala
- src/main/scala/strawman/collection/View.scala
- test/junit/src/test/scala/strawman/collection/IteratorTest.scala
- test/junit/src/test/scala/strawman/collection/SeqTest.scala
- test/junit/src/test/scala/strawman/collection/StrictOptimizedSeqTest.scala
Addresses #239:
- Add `distinctBy` operation and re-write `distinct` in terms of `distinctBy`
- Add unit tests and benchmarks for `distinctBy`
> Add distinctBy operation

- README.md
- src/main/scala/strawman/collection/Map.scala
- src/main/scala/strawman/collection/mutable/LinkedHashMap.scala
- src/main/scala/strawman/collection/mutable/LinkedHashSet.scala
- test/junit/src/test/scala/strawman/collection/mutable/LinkedHashMapTest.scala
- test/junit/src/test/scala/strawman/collection/mutable/LinkedHashSetTest.scala
> Add LinkedHashSet and LinkedHashMap

- README.md
- collections-contrib/src/main/scala/strawman/collection/decorators/MapDecorator.scala
- collections-contrib/src/test/scala/strawman/collection/decorators/MapDecoratorTest.scala
Add zipByKey/join, mergeByKeyWith, mergeByKey/fullOuterJoin, leftOuterJoin,
rightOuterJoin
Fixes #71
/cc @pfcoperez
> Add more join operations

- collections/src/main/scala/strawman/collection/immutable/NumericRange.scala
- test/junit/src/test/scala/strawman/collection/NumericRangeTest.scala
> Fix empty iterator in NumericRange

- collections/src/main/scala/strawman/collection/Iterable.scala
- collections/src/main/scala/strawman/collection/Seq.scala
> Implement concat in terms of :++ in Seq so that it benefits from perf overrides

- collections/src/main/scala/strawman/collection/mutable/ArrayBuffer.scala
- collections/src/main/scala/strawman/collection/mutable/ListBuffer.scala
> Make ListBuffer and ArrayBuffer serializable.

- collections/src/main/scala/strawman/collection/SortedMap.scala
- collections/src/main/scala/strawman/collection/SortedOps.scala
- collections/src/main/scala/strawman/collection/SortedSet.scala
- collections/src/main/scala/strawman/collection/immutable/RedBlackTree.scala
- collections/src/main/scala/strawman/collection/immutable/TreeMap.scala
- collections/src/main/scala/strawman/collection/immutable/TreeSet.scala
- collections/src/main/scala/strawman/collection/mutable/TreeMap.scala
- collections/src/main/scala/strawman/collection/mutable/TreeSet.scala
- test/scalacheck/src/test/scala/strawman/collection/mutable/MutableTreeMap.scala
- test/scalacheck/src/test/scala/strawman/collection/mutable/MutableTreeSet.scala
- test/scalacheck/src/test/scala/treemap.scala
- test/scalacheck/src/test/scala/treeset.scala
> Add `maxBefore` and `minAfter` methods to `TreeMap` and `TreeSet`

- collections/src/main/scala/strawman/collection/Iterable.scala
- collections/src/main/scala/strawman/collection/Iterator.scala
- collections/src/main/scala/strawman/collection/Map.scala
- collections/src/main/scala/strawman/collection/SortedMap.scala
- collections/src/main/scala/strawman/collection/SortedSet.scala
- collections/src/main/scala/strawman/collection/View.scala
- collections/src/main/scala/strawman/collection/mutable/ArrayBuffer.scala
- collections/src/main/scala/strawman/collection/mutable/ListBuffer.scala
Completes previous work on #143
> Add some missing API docs

- collections/src/main/scala/strawman/collection/Iterator.scala
- collections/src/main/scala/strawman/collection/View.scala
- collections/src/main/scala/strawman/collection/immutable/NumericRange.scala
- collections/src/main/scala/strawman/collection/immutable/Range.scala
- collections/src/main/scala/strawman/collection/immutable/Vector.scala
- test/junit/src/test/scala/strawman/collection/IteratorTest.scala
Override it for indexed sequence iterators to return the number of
remaining elements.
Fixes #323.
> Make knownSize non final on Iterator

- benchmarks/time/src/main/scala/strawman/collection/immutable/HashSetBenchmark.scala
- benchmarks/time/src/main/scala/strawman/collection/immutable/ImmutableArrayBenchmark.scala
- benchmarks/time/src/main/scala/strawman/collection/immutable/LazyListBenchmark.scala
- benchmarks/time/src/main/scala/strawman/collection/immutable/ListBenchmark.scala
- benchmarks/time/src/main/scala/strawman/collection/immutable/NumericRangeBenchmark.scala
- benchmarks/time/src/main/scala/strawman/collection/immutable/RangeBenchmark.scala
- benchmarks/time/src/main/scala/strawman/collection/immutable/TreeSetBenchmark.scala
- benchmarks/time/src/main/scala/strawman/collection/immutable/VectorBenchmark.scala
- benchmarks/time/src/main/scala/strawman/collection/mutable/ArrayBufferBenchmark.scala
- benchmarks/time/src/main/scala/strawman/collection/mutable/ListBufferBenchmark.scala
- collections/src/main/scala/strawman/collection/ArrayOps.scala
- collections/src/main/scala/strawman/collection/Iterable.scala
- collections/src/main/scala/strawman/collection/IterableOnce.scala
- collections/src/main/scala/strawman/collection/Iterator.scala
- collections/src/main/scala/strawman/collection/Seq.scala
- collections/src/main/scala/strawman/collection/Set.scala
- collections/src/main/scala/strawman/collection/StrictOptimizedIterableOps.scala
- collections/src/main/scala/strawman/collection/StringOps.scala
- collections/src/main/scala/strawman/collection/View.scala
- collections/src/main/scala/strawman/collection/generic/package.scala
- collections/src/main/scala/strawman/collection/immutable/List.scala
- collections/src/main/scala/strawman/collection/immutable/Seq.scala
- collections/src/main/scala/strawman/collection/immutable/package.scala
- collections/src/main/scala/strawman/collection/mutable/Buffer.scala
- collections/src/main/scala/strawman/collection/mutable/Builder.scala
- collections/src/main/scala/strawman/collection/mutable/IndexedSeq.scala
- collections/src/main/scala/strawman/collection/mutable/Set.scala
- collections/src/main/scala/strawman/collection/mutable/package.scala
- collections/src/main/scala/strawman/collection/package.scala
- collections/src/test/scala/strawman/collection/test/Test.scala
Another bunch of minor bug fixes and compatibility changes from my scala-integration branch
> Various bug fixes, additional methods and deprecated forwarders

- collections/src/main/scala/strawman/collection/convert/Wrappers.scala
- collections/src/main/scala/strawman/collection/mutable/AnyRefMap.scala
- collections/src/main/scala/strawman/collection/mutable/Builder.scala
- collections/src/main/scala/strawman/collection/mutable/LongMap.scala
Our own code base were raising a few warnings. This PR addresses them.
> Address warnings

- collections/src/main/scala/strawman/collection/Iterator.scala
- test/junit/src/test/scala/strawman/collection/IteratorTest.scala
> Fix NPE in Iterator.addString when there are null elements

- collections/src/main/scala/strawman/collection/mutable/ArrayBuffer.scala
- test/junit/src/test/scala/strawman/collection/mutable/ArrayBufferTest.scala
> Increment end in Buffer.insert

- collections/src/main/scala/strawman/collection/mutable/Buffer.scala
> Make Buffer implement SeqOps to retain original type after invoking operations on it

- collections/src/main/scala/strawman/collection/ArrayOps.scala
- test/junit/src/test/scala/strawman/collection/ArrayOpsTest.scala
> Overload unzip in ArrayOps

- collections/src/main/scala/strawman/collection/mutable/Buffer.scala
- collections/src/main/scala/strawman/collection/mutable/ListBuffer.scala
- test/junit/src/test/scala/strawman/collection/mutable/ArrayBufferTest.scala
- test/junit/src/test/scala/strawman/collection/mutable/ListBufferTest.scala
> Fix ArrayBuffer/ListBuffer flatMapInPlace

- collections/src/main/scala/strawman/collection/mutable/LinkedList.scala
- collections/src/main/scala/strawman/collection/mutable/MutableList.scala
- collections/src/main/scala/strawman/collection/mutable/Queue.scala
The branch was outdated without causing proper merge conflicts.
> Fix problems caused by merging #336

- .travis.yml
perhaps this will make snapshots start publishing themselves again
references #451
> fix typo in .travis.yml

- collections/src/main/scala/strawman/collection/mutable/package.scala
The old AraySeq was never specialized, so this is the closest
equivalent that we have.
> Use WrappedArray’s iterableFactory for ArraySeq

- collections/src/main/scala/strawman/collection/ArrayOps.scala
Discovered by the compiler test suite
> Fix some ArrayOps bugs

- collections/src/main/scala/strawman/collection/immutable/Vector.scala
> Add size methods to VectorBuilder

- collections/src/main/scala/strawman/collection/convert/AsJavaConverters.scala
- collections/src/main/scala/strawman/collection/convert/WrapAsJava.scala
- collections/src/main/scala/strawman/collection/convert/Wrappers.scala
- collections/src/main/scala/strawman/collection/mutable/WeakHashMap.scala
Fixes scala/collection-strawman#402
> Make transformation operations of WeakHashMap return WeakHashMaps

- collections/src/main/scala/strawman/collection/Iterable.scala
- collections/src/main/scala/strawman/collection/IterableOnce.scala
- collections/src/main/scala/strawman/collection/Iterator.scala
- collections/src/main/scala/strawman/collection/LinearSeq.scala
- collections/src/main/scala/strawman/collection/Seq.scala
- collections/src/main/scala/strawman/collection/concurrent/TrieMap.scala
- collections/src/main/scala/strawman/collection/generic/BitOperations.scala
- collections/src/main/scala/strawman/collection/immutable/HashMap.scala
- collections/src/main/scala/strawman/collection/immutable/LazyList.scala
- collections/src/main/scala/strawman/collection/immutable/ListMap.scala
- collections/src/main/scala/strawman/collection/immutable/LongMap.scala
- collections/src/main/scala/strawman/collection/immutable/Map.scala
- collections/src/main/scala/strawman/collection/immutable/RedBlackTree.scala
- collections/src/main/scala/strawman/collection/immutable/Seq.scala
- collections/src/main/scala/strawman/collection/immutable/TreeMap.scala
- collections/src/main/scala/strawman/collection/immutable/TreeSet.scala
- collections/src/main/scala/strawman/collection/mutable/ArrayBuffer.scala
- collections/src/main/scala/strawman/collection/mutable/BitSet.scala
- collections/src/main/scala/strawman/collection/mutable/Builder.scala
- collections/src/main/scala/strawman/collection/mutable/HashMap.scala
- collections/src/main/scala/strawman/collection/mutable/HashSet.scala
- collections/src/main/scala/strawman/collection/mutable/ListBuffer.scala
- collections/src/main/scala/strawman/collection/mutable/WeakHashMap.scala
- test/junit/src/test/scala/strawman/collection/IterableTest.scala
- test/junit/src/test/scala/strawman/collection/IteratorTest.scala
- test/junit/src/test/scala/strawman/collection/LinearSeqOptimizedTest.scala
- test/junit/src/test/scala/strawman/collection/mutable/BitSetTest.scala
I went through the history of the collections on the scala/scala repo, for the last year, and backported all the things that were missing in the strawman.
Fixes #214.
> Fixes from scala/scala repository
